#############################################################################
# Makefile for building: qt-helloworld
# Generated by qmake (3.1) (Qt 6.2.4)
# Project:  qt-helloworld.pro
# Template: app
# Command: /opt/qt/6.2.4/gcc_64/bin/qmake -o Makefile qt-helloworld.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/opt/qt/6.2.4/gcc_64/include -I/opt/qt/6.2.4/gcc_64/include/QtWidgets -I/opt/qt/6.2.4/gcc_64/include/QtGui -I/opt/qt/6.2.4/gcc_64/include/QtCore -I. -I/opt/qt/6.2.4/gcc_64/mkspecs/linux-g++
QMAKE         = /opt/qt/6.2.4/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/qt/6.2.4/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/qt/6.2.4/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qt-helloworld1.0.0
DISTDIR = /home/jeremy/apps/_mozilla/edu/qt-helloworld/.tmp/qt-helloworld1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qt/6.2.4/gcc_64/lib -Wl,-rpath-link,/opt/qt/6.2.4/gcc_64/lib
LIBS          = $(SUBLIBS) /opt/qt/6.2.4/gcc_64/lib/libQt6Widgets.so /opt/qt/6.2.4/gcc_64/lib/libQt6Gui.so /opt/qt/6.2.4/gcc_64/lib/libQt6Core.so -lpthread -lGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = qt-helloworld.cpp 
OBJECTS       = qt-helloworld.o
DIST          = /opt/qt/6.2.4/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/common/unix.conf \
		/opt/qt/6.2.4/gcc_64/mkspecs/common/linux.conf \
		/opt/qt/6.2.4/gcc_64/mkspecs/common/sanitize.conf \
		/opt/qt/6.2.4/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/qt/6.2.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/qt/6.2.4/gcc_64/mkspecs/common/g++-base.conf \
		/opt/qt/6.2.4/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/qt/6.2.4/gcc_64/mkspecs/qconfig.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_chartsqml.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_core5compat.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_core5compat_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3deffects.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicktimeline.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_scxmlqml.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_sensorsquick.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_shadertools.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_statemachine.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_statemachine_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_statemachineqml.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginequick.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webviewquick.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/qt_config.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/toolchain.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/default_pre.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/default_post.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/warn_on.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/qt.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/resources_functions.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/resources.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/moc.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/uic.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/qmake_use.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/file_copies.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/exceptions.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/yacc.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/lex.prf \
		qt-helloworld.pro  qt-helloworld.cpp
QMAKE_TARGET  = qt-helloworld
DESTDIR       = 
TARGET        = qt-helloworld


first: all
####### Build rules

qt-helloworld:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qt-helloworld.pro /opt/qt/6.2.4/gcc_64/mkspecs/linux-g++/qmake.conf /opt/qt/6.2.4/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/common/unix.conf \
		/opt/qt/6.2.4/gcc_64/mkspecs/common/linux.conf \
		/opt/qt/6.2.4/gcc_64/mkspecs/common/sanitize.conf \
		/opt/qt/6.2.4/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/qt/6.2.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/qt/6.2.4/gcc_64/mkspecs/common/g++-base.conf \
		/opt/qt/6.2.4/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/qt/6.2.4/gcc_64/mkspecs/qconfig.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_chartsqml.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_core5compat.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_core5compat_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3deffects.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicktimeline.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_scxmlqml.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_sensorsquick.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_shadertools.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_statemachine.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_statemachine_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_statemachineqml.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginequick.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webviewquick.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/qt_config.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/toolchain.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/default_pre.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/default_post.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/warn_on.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/qt.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/resources_functions.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/resources.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/moc.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/uic.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/qmake_use.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/file_copies.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/exceptions.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/yacc.prf \
		/opt/qt/6.2.4/gcc_64/mkspecs/features/lex.prf \
		qt-helloworld.pro \
		/opt/qt/6.2.4/gcc_64/lib/libQt6Widgets.prl \
		/opt/qt/6.2.4/gcc_64/lib/libQt6Gui.prl \
		/opt/qt/6.2.4/gcc_64/lib/libQt6Core.prl
	$(QMAKE) -o Makefile qt-helloworld.pro
/opt/qt/6.2.4/gcc_64/mkspecs/features/spec_pre.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/common/unix.conf:
/opt/qt/6.2.4/gcc_64/mkspecs/common/linux.conf:
/opt/qt/6.2.4/gcc_64/mkspecs/common/sanitize.conf:
/opt/qt/6.2.4/gcc_64/mkspecs/common/gcc-base.conf:
/opt/qt/6.2.4/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/qt/6.2.4/gcc_64/mkspecs/common/g++-base.conf:
/opt/qt/6.2.4/gcc_64/mkspecs/common/g++-unix.conf:
/opt/qt/6.2.4/gcc_64/mkspecs/qconfig.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_ext_libpng.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_chartsqml.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_chartsqml_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_core5compat.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_core5compat_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labssettings.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_linguist.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3d.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3deffects.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dparticles.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicktimeline.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_scxmlqml.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_sensorsquick.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_shadertools.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_shadertools_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_statemachine.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_statemachine_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_statemachineqml.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_tools_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginequick.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginequick_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webviewquick.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_webviewquick_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt/6.2.4/gcc_64/mkspecs/features/qt_functions.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/qt_config.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/qt/6.2.4/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/toolchain.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/default_pre.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/resolve_config.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/default_post.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/warn_on.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/qt.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/resources_functions.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/resources.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/moc.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/uic.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/unix/thread.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/qmake_use.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/file_copies.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/exceptions.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/yacc.prf:
/opt/qt/6.2.4/gcc_64/mkspecs/features/lex.prf:
qt-helloworld.pro:
/opt/qt/6.2.4/gcc_64/lib/libQt6Widgets.prl:
/opt/qt/6.2.4/gcc_64/lib/libQt6Gui.prl:
/opt/qt/6.2.4/gcc_64/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qt-helloworld.pro

qmake_all: FORCE


all: Makefile qt-helloworld

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/qt/6.2.4/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents qt-helloworld.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/qt/6.2.4/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /opt/qt/6.2.4/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

qt-helloworld.o: qt-helloworld.cpp /opt/qt/6.2.4/gcc_64/include/QtWidgets/QApplication \
		/opt/qt/6.2.4/gcc_64/include/QtWidgets/qapplication.h \
		/opt/qt/6.2.4/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qtguiglobal.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qglobal.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qconfig.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qtcore-config.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qlogging.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qflags.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qatomic.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qversiontagging.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qtgui-config.h \
		/opt/qt/6.2.4/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qstring.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qchar.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qstringview.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qtmetamacros.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qpair.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qarraydatapointer.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qarraydataops.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcontainertools_impl.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qbytearrayview.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qstringliteral.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qanystringview.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qutf8stringview.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qstringtokenizer.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qeventloop.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qobject.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qlist.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qiterator.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcompare.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qscopeguard.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qiodevicebase.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qiterable.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qmetacontainer.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcontainerinfo.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qtaggedpointer.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qmath.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qbindingstorage.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qnativeinterface.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qdebug.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qhash.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qmap.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qshareddata_impl.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qstringconverter.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qset.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcoreapplication_platform.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qfuture.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qfutureinterface.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qmutex.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qresultstore.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qfuture_impl.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qthreadpool.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qthread.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qdeadlinetimer.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qelapsedtimer.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qrunnable.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qexception.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qpointer.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qpromise.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qvariant.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qpoint.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qsize.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qmargins.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qcursor.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qbitmap.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qrect.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qcolor.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qrgb.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qrgba64.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qimage.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qtransform.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qregion.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qline.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qguiapplication.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qinputmethod.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qlocale.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qguiapplication_platform.h \
		/opt/qt/6.2.4/gcc_64/include/QtWidgets/QLabel \
		/opt/qt/6.2.4/gcc_64/include/QtWidgets/qlabel.h \
		/opt/qt/6.2.4/gcc_64/include/QtWidgets/qframe.h \
		/opt/qt/6.2.4/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qpalette.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qbrush.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qfont.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt/6.2.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qevent.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qurl.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qeventpoint.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qvectornd.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qpointingdevice.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qinputdevice.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qscreen.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/QList \
		/opt/qt/6.2.4/gcc_64/include/QtCore/QObject \
		/opt/qt/6.2.4/gcc_64/include/QtCore/QRect \
		/opt/qt/6.2.4/gcc_64/include/QtCore/QSize \
		/opt/qt/6.2.4/gcc_64/include/QtCore/QSizeF \
		/opt/qt/6.2.4/gcc_64/include/QtGui/QTransform \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qpicture.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qtextdocument.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/QtGui \
		/opt/qt/6.2.4/gcc_64/include/QtGui/QtGuiDepends \
		/opt/qt/6.2.4/gcc_64/include/QtCore/QtCore \
		/opt/qt/6.2.4/gcc_64/include/QtCore/QtCoreDepends \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qabstractanimation.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qabstractnativeeventfilter.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qabstractproxymodel.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qanimationgroup.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qassociativeiterable.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qbasictimer.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qbitarray.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qbuffer.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qbytearraymatcher.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcache.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcalendar.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcborarray.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcborvalue.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qdatetime.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcborcommon.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qregularexpression.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/quuid.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcbormap.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcborstream.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcborstreamreader.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qfloat16.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcborstreamwriter.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcollator.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcommandlineoption.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcommandlineparser.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qconcatenatetablesproxymodel.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qcryptographichash.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qdir.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qfile.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qfileinfo.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qdiriterator.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qeasingcurve.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qendian.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qfactoryinterface.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qfileselector.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/QStringList \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qfilesystemwatcher.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qfuturesynchronizer.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qfuturewatcher.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qidentityproxymodel.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qitemselectionmodel.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qjnienvironment.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/QScopedPointer \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qjniobject.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qjsonarray.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qjsonvalue.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qjsondocument.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qjsonobject.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qlibrary.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qlibraryinfo.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qversionnumber.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qlockfile.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qloggingcategory.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qmessageauthenticationcode.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qmetaobject.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qmimedata.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qmimedatabase.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qmimetype.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qobjectcleanuphandler.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qoperatingsystemversion.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qparallelanimationgroup.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qpauseanimation.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qplugin.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qpluginloader.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qprocess.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qproperty.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qpropertyprivate.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qpropertyanimation.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qvariantanimation.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qqueue.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qrandom.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qreadwritelock.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qresource.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qsavefile.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qscopedvaluerollback.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qsemaphore.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qsequentialanimationgroup.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qsequentialiterable.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qsettings.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qsharedmemory.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qsignalmapper.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qsimd.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qsocketnotifier.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qsortfilterproxymodel.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qstack.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qstandardpaths.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qstorageinfo.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qstringlistmodel.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qsystemsemaphore.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qtemporarydir.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qtemporaryfile.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qtextboundaryfinder.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qthreadstorage.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qtimeline.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qtimer.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qtimezone.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qtranslator.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qtransposeproxymodel.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qvector.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qwaitcondition.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/QDeadlineTimer \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qwineventnotifier.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qxmlstream.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qtcoreversion.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qabstractfileiconprovider.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qicon.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qabstracttextdocumentlayout.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qtextlayout.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qglyphrun.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qrawfont.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qfontdatabase.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qtextcursor.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qtextformat.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qpen.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qaccessible.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qaccessiblebridge.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qaccessibleobject.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qaccessibleplugin.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qaction.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qactiongroup.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qbackingstore.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qwindow.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/QEvent \
		/opt/qt/6.2.4/gcc_64/include/QtCore/QMargins \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qsurface.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qsurfaceformat.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qclipboard.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qcolorspace.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qcolortransform.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qdesktopservices.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qdrag.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qfilesystemmodel.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qgenericmatrix.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qgenericplugin.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qgenericpluginfactory.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qiconengine.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qiconengineplugin.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qimageiohandler.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qimagereader.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qimagewriter.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qmatrix4x4.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qvector3d.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qvector4d.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qquaternion.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qmovie.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qoffscreensurface.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qoffscreensurface_platform.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qopengl.h \
		/opt/qt/6.2.4/gcc_64/include/QtCore/qt_windows.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qopenglext.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qopenglcontext.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qopenglcontext_platform.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qopenglextrafunctions.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qopenglfunctions.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qpagedpaintdevice.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qpagelayout.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qpagesize.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qpageranges.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qpaintdevicewindow.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/QWindow \
		/opt/qt/6.2.4/gcc_64/include/QtGui/QPaintDevice \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qpaintengine.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qpainter.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qpdfwriter.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qpixmapcache.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qrasterwindow.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/QPaintDeviceWindow \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qrgbafloat.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qsessionmanager.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qshortcut.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qstandarditemmodel.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qstatictext.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qstylehints.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qsyntaxhighlighter.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qtextobject.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qtextdocumentfragment.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qtextdocumentwriter.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qtextlist.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qtexttable.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qundogroup.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qundostack.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qvalidator.h \
		/opt/qt/6.2.4/gcc_64/include/QtGui/qtguiversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qt-helloworld.o qt-helloworld.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

